### ISSUE TITLE
log directory is not created when pkt_kg is imported

### ISSUE THREAD

**Issue by bsantan** [callahantiff/PheKnowLator#95] opened 2021-03-29 23:46 UTC
**Describe the bug**
In OWLNETS_Example_Application.ipynb get this error
<img width="806" alt="Screen Shot 2021-03-29 at 5 46 20 PM" src="https://user-images.githubusercontent.com/70932395/112913351-ad3f8180-90b6-11eb-888e-9596fef2f89d.png">

**To Reproduce**
1. Go to ‘...’
2. Click on ‘....’
3. Scroll down to ‘....’

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by callahantiff** [comment] 2021-03-30 02:46
Hey! Since I can't reproduce this error on BigSur, Catalina, Linux Debian, or High Sierra I suspect there is something else going on specific to your set-up. Happy to help you figure it out though. In the meantime I am going to close this. If we can't get it working after the next release let's re-open it.

**Closed by callahantiff** 2021-03-30 02:46 UTC
Labels: bug
