### ISSUE TITLE
Disappearing edges when creating KG

### ISSUE THREAD

**Issue by GuarinoValentina** [callahantiff/PheKnowLator#140] opened 2023-11-15 10:36 UTC
Hi Tiffany, sorry to bother you!
I'm using PheKnowLator to construct a KG. At first, I succeeded to construct an initial KG with edges: gene-disease (that I further splitted in gene-diseaseInhib and gene-diseaseProm, due to different relations), gene-cell and protein-disease.
However, I have some troubles when trying to add relations of type chemical-disease or chemical-protein.
In particular, I have 2 different chemical databases: for the first one I have PubChem ID as chemical identifiers (which I defined as subclass of CHEBI_50846 "immunomodulator" in the subclass_construction_map.pkl file) while for the other one I have a direct mapping on the ChEBI ontology. 
The Master_Edge_List_Dict file correctly contains all the considered edges but, when the building KG step is performed, I lose some edges. I think that the problem is related to the chemicalPC-protein and the chemicalChebi-protein edges: when I delete them I can create the KG with all the remaining edges, but if there's even only one of that chemical-protein edge some other edge will disappear. For example, in the output of Building KG step that I'm attaching to you (using all the complete list of edges), 2 edges are lost: chemicalChebi-protein and chemicalPC-disease. 
I tried to swap positions in edge_source_list file, I checked for any special characters in the .txt files that could cause this issue, but I can't understand why this happen. I checked the .txt files, the resource_info and the edge_source_list files, and they seem correct to me. Can you help me?
Looking forward to hearing from you,
thank you 
Valentina
<img width="1021" alt="BuildingKG_output" src="https://github.com/callahantiff/PheKnowLator/assets/80695276/0b7f60b3-92c8-43ab-b33f-640d1cb22c64">
[chemicals_protein_CHEBI_map.txt](https://github.com/callahantiff/PheKnowLator/files/13363362/chemicals_protein_CHEBI_map.txt)
[chemicals_protein_PC_map.txt](https://github.com/callahantiff/PheKnowLator/files/13363363/chemicals_protein_PC_map.txt)
[edge_source_list.txt](https://github.com/callahantiff/PheKnowLator/files/13363364/edge_source_list.txt)
[ontology_source_list.txt](https://github.com/callahantiff/PheKnowLator/files/13363365/ontology_source_list.txt)
[resource_info.txt](https://github.com/callahantiff/PheKnowLator/files/13363366/resource_info.txt)
[Master_Edge_List_Dict-2.json](https://github.com/callahantiff/PheKnowLator/files/13363387/Master_Edge_List_Dict-2.json)

**Comment by callahantiff** [comment] 2023-11-15 22:56
Hey @GuarinoValentina!

Thanks so much for using `PheKnowLator` and for reaching out. I reviewed your message and believe that I know where the problem is. I think it will be easier (and certainly more fun) if we set-up a virtual meeting to discuss. I will reach out to you via email to set something up.

**Comment by callahantiff** [comment] 2023-11-18 16:23
Everything should be fixed with the latest release [`v3.1.2`](https://github.com/callahantiff/PheKnowLator/releases/tag/v3.1.2). Thank you again for brining this to my attention, I hope it didn't cause you too much trouble. I am going to close this issue. Please feel free to re-open or make a new issue if you encounter anything else. Thanks so much!

**Closed by callahantiff** 2023-11-18 16:23 UTC
Labels: other

**Comment by sanyabt** [comment] 2024-03-06 20:52
Hi @callahantiff, not sure if this is the right place but I was tracking this issue while updating to v3.1.2 and after updating, owltools is throwing exceptions in the Ontology_Cleaning.ipynb notebook. I checked on command line and the owltools package in pkt_kg/ seems to be throwing errors as well. I can open a new issue if you'd like but thought might be relevant here. Thanks!

**Comment by callahantiff** [comment] 2024-03-07 03:00
> Hi @callahantiff, not sure if this is the right place but I was tracking this issue while updating to v3.1.2 and after updating, owltools is throwing exceptions in the Ontology_Cleaning.ipynb notebook. I checked on command line and the owltools package in pkt_kg/ seems to be throwing errors as well. I can open a new issue if you'd like but thought might be relevant here. Thanks!

Hey @sanyabt - thanks for your message. It's odd that owltools is acting up. Nothing that was changed related to the original issue filed above touched owltools. So, I am wondering if it's a dependencies thing. I did see owlnets throwing warnings a while ago but it had no impact on the code running.

Could you please provide the error message you are getting and what you ran that triggered it?

For the sake of completeness, would you by chance be willing to try replacing your current version of owltools with one from a prior release? You can access the file from the zipped source_code ([here](https://github.com/callahantiff/PheKnowLator/archive/refs/tags/v3.1.0.zip), for example).

**Comment by callahantiff** [comment] 2024-03-07 22:16
Hey @sanyabt -- just an update. I had a chance to run the `Ontology_Cleaning.ipynb` notebook today and was able to run it from start to finish without any issues.

This is good news overall; I was worried that it is was going to be something scary that required replacing `owltools` (which would be a big job given how much it's used in pkt). That said, I want to help you get things running on your end if I can!

Keep me posted!

**Comment by sanyabt** [comment] 2024-03-07 22:19
Thank you for letting me know! It might just be an owl tools or dependency issue on my environment then in which case I'm sorry for worrying you! I'll try running the notebook again with the new and old version of owl tools and let you know. Was planning to do it today but didn't get the time. Thanks again for checking!!
